### PR TITLE
Feature-polkadot support

### PR DESCRIPTION
**Pull request by sahilnanda1995**

### CODE REVIEW

**Review by saumyakaran — CHANGES_REQUESTED** [review]
@sahilnanda1995 In general, looks good to go... Just a few small issues which need to be fixed:

On the payment page, the content needs to be dynamic (28eras on polkadot is ~28 days):
Screenshot 2020-10-20 at 11 24 46 AM

"Track on subscan" leads to kusama.subscan link instead of polkadot - this needs to be network specific too:

Screenshot 2020-10-20 at 11 27 12 AM

PS - [Not important for this PR] I saw that I could be earning ~73% APY!

1. Is this correct?
2. On a tangential note, have we filtered the oversubscribed validators from our recommendations?

Screenshot 2020-10-20 at 11 30 20 AM

**Comment by sahilnanda1995** [comment]
> Is this correct?
it should be

>On a tangential note, have we filtered the oversubscribed validators from our recommendations?
No, that will be tackled in the next sprint

Also, did you try staking?

**Comment by saumyakaran** [comment]
> Also, did you try staking?

Yes - worked fine.

**Review by saumyakaran — APPROVED** [review]

**Comment by prastut** [comment]
Polkadot offers 73% staking?! 

https://www.stakingrewards.com/earn/polkadot
is saying it offers 4%

Though I know that we are more accurate than staking rewards but it would be good to double-check this. 

This APR is probably not being offered by anybody on staking in the blockchain space.

**Comment by sahilnanda1995** [comment]
fixed the rewards for, now it makes more sense😅
@saumyakaran @prastut

**Pull request merged**
