### PR TITLE
fixed disabled updating nominations for max amount + dependencies upgrade

### PR DESCRIPTION
**Pull request by sahilnanda1995**

### CODE REVIEW

**Comment by sahilnanda1995** [comment]
@saumyakaran @prastut requesting to thoroughly test this PR before approving

**Comment by saumyakaran** [comment]
1. UI allowed me to input a higher staking amount than I could and continued should that all the way till I successfully sent tx to chain and the tx actually went through with a lower amount staked than what was shown to me.
2. Because all my funds got locked because of the above, I have no way to withdraw my funds any more.

**Comment by saumyakaran** [comment]
**Not as critical but still an issue:**

Reward calculator loads without data first:
Screenshot 2020-12-18 at 2 37 46 PM

To recreate visit calculator using a clean browser or incognito window

**Review by saumyakaran — APPROVED** [review]
Approving based on trusting @sahilnanda1995's judgement

**Pull request merged**
