### PR TITLE
Landing page testimonial UI fixes

### PR DESCRIPTION
**Pull request by saumyakaran**
- Fix: testimonials are now the same size

### CODE REVIEW

**Review by prastut — APPROVED** [review]

**Comment by sahilnanda1995** [comment]
are these ready to merge?

**Comment by saumyakaran** [comment]
@sahilnanda1995 yes

**Comment by sahilnanda1995** [comment]
@saumyakaran these changes break home page UI

**Comment by saumyakaran** [comment]
@sahilnanda1995 Can you be more specific? What exactly does this break?

**Comment by sahilnanda1995** [comment]
> @sahilnanda1995 Can you be more specific? What exactly does this break?

created an issue [here](https://github.com/buidl-labs/yieldscan-frontend/issues/163#issue-756286754)

**Pull request merged**
