### PR TITLE
Performance fixes

### PR DESCRIPTION
**Pull request by sahilnanda1995**

### CODE REVIEW

**Comment by saumyakaran** [comment]
https://sentry.io/organizations/buidl-labs-3g/issues/2082552257/?project=5399113&query=is%3Aunresolved

cc @sahilnanda1995

**Comment by sahilnanda1995** [comment]
@saumyakaran and @prastut test it out and let me know any changes

**Review by saumyakaran — CHANGES_REQUESTED** [review]
## Context
I assumed that this PR was supported to close the [Onboarding flow fixes](https://github.com/buidl-labs/yieldscan-frontend/projects/4) project

### Disclaimer
I didn't have a way to test the disabling of staking activities during elections - so that's untested

## Feedback

### Homepage
- The homepage UI is still broken - probably merging #177 to this branch should fix this

### Overview

- Overview tab loads multiple times: https://file.video/v/a0d6d204-e8e7-40b7-9807-186168751635
- Switching accounts causes a similar issue to multiple loading: https://file.video/v/b55db257-101d-4045-9b5b-66bb4f7748c2
- Earnings output isn't displayed for users with inactive validators:
Screenshot 2020-12-11 at 11 03 06 AM

### Header

- Total balance on yieldscan (68.3166 KSM) doesn't match total balance on subscan (69.9832 KSM) - [see on subscan](https://kusama.subscan.io/account/Eksmah4LfMN3wbVggUxftDnFr8J2sGhKUV84Yw7QHsox1iN?tab=reward)

### Calculator

- There's some weird issue with header loading where a loading spinner appears in the middle of reward calculator page:
Screenshot 2020-12-10 at 7 37 52 PM

- When the input is empty and I switch time period unit, the results don't change

---

### Design issues

- [Design issue] Clicking on the max button for "invest more" input on overview tab - if I have 0 transferrable balance, it inputs -0.1 -> also doesn't show any error
- [Design issue] Withdrawal input doesn't take into account the case if there are no funds to be unlocked - i.e. if all of their funds are already unlocking

**Comment by sahilnanda1995** [comment]
> Total balance on yieldscan (68.3166 KSM) doesn't match total balance on subscan (69.9832 KSM)

i have intentionally removed reserved balance from the total balance display, that's why

**Comment by saumyakaran** [comment]
> i have intentionally removed reserved balance from the total balance display, that's why

Let's discuss this on a call

**Comment by sahilnanda1995** [comment]
> There's some weird issue with header loading where a loading spinner appears in the middle of reward calculator page:

that is also intentional, much better to discuss it on a call

**Comment by sahilnanda1995** [comment]
> Switching accounts causes a similar issue to multiple loading: https://file.video/v/b55db257-101d-4045-9b5b-66bb4f7748c2

@saumyakaran  which browser are you using?

**Comment by saumyakaran** [comment]
- [ ] Change text from “Invest now” to “Proceed to confirmation” on reward calculator and validators page
- [ ] Remove scrollbar -> display all by default (but the user does need to open the suggested validators collapsed thingy) - closes #183

**Review by saumyakaran — APPROVED** [review]
Pre-approving based on trusting @sahilnanda1995's judgement

**Pull request merged**
