### PR TITLE
sprint/week-3

### LINKED ISSUE #15: Dashboard overview requirements
# TODO

### 🗒 &nbsp; Summary

Requirements that need to be fulfilled by the "Dashboard - Overview" page.

### ✅ &nbsp; Outcomes

I (as a user) should be able to:

- [x] View the current status of my investments with some indication of how those investments are doing
       - [ ] [To be done later] Answer the question "do I need to change them for optimal returns?"

- [x] Change my selected validators without having to go through the entire payment process - i.e. "quick change" of sorts

- [x] Change my payment destination (where my rewards are being transferred to) - again "quick change"

- [x] Change the controller being used - again "quick change"

~- [ ] See claimable rewards + Claim rewards for specific or all validators~

- [x] Unbond funds - sort of "quick unbond" - i.e. not going through the entire payment process.

- [x] Bond more funds - "quick bond"

- [x] Stop all nominations - I would also want to be prompted for unbonding my funds if I click the "stop all" button

## ⏳ &nbsp; ETA

Not updated yet

If you don't specify a timezone, by default IST shall be assumed.

Refer: [ETA culture document](https://docs.google.com/document/d/1ZGa6diesOmx-jSBjm0uj8j4oN75gYqux85qA7DJOm68/edit)

### LINKED ISSUE #27: [BUG] Amount in funds-update not in KSM
**Describe the bug**
Amount sent to chain transaction in `funds-update` not in KSM but in milli or some other small power, figure it out and fix it.

### PR DESCRIPTION
**Pull request by akshatbhargava123**
PR closes #15 and closes #27 . 
Considers #20 for status.

### CODE REVIEW

**Comment by saumyakaran** [comment]
@akshatbhargava123 Feedback:

1. Regarding the "quick change" for payment destination - it says "successful" but the transaction doesn't seem to be getting registered on the chain (not even a failed tx) - https://polkascan.io/kusama/account/DFju6tr8e9TLrJZZD4kdpmm3cG4GnVF9RDRDdZdfAU3cXff

Even tried changing the controller being used: https://polkascan.io/kusama/account/EUX7WK7bg5o8wgyvyNNBcUMbKGrgjFqqLyRczLPPa96SDNL

2. We need a loader while the tx is being processed to let the user know that that's happening + not allow them to send more txs using the UI while the tx is still being processed

3. We need to display an "unbonding balance" similar to polkadotJS UI (SS below) - we could probably add this on the "staked amount" card on the overview tab itself

Screenshot 2020-07-04 at 11 13 21 AM

4. When trying to bond more funds, I get an error (SS below) - probably because we're using a controller for signing this instead of the stash:

Screenshot 2020-07-04 at 11 20 32 AM
Source: https://polkascan.io/kusama/transaction/0x5731da94f765dc44e441ab24f7c1a115aea39706ccabf4e477289a8fa2574f6f

5. On the "Stop all nominations" action, I get the following error:

Screenshot 2020-07-04 at 11 22 27 AM

PS - I just noticed that after making changes to my account preferences - like bonding/unbonding, changing nominations, etc. it doesn't show in the overview - this is probably because we're not showing realtime data - this needs to be realtime.


I've only reviewed the overview tab for now, since it's pointless to move forward without getting this right.

**Comment by akshatbhargava123** [comment]
@saumyakaran 

> We need a loader while the tx is being processed to let the user know that that's happening + not allow them to send more txs using the UI while the tx is still being processed

Could you please elaborate where the loader is not visible, I've taken care of this at most places.

> We need to display an "unbonding balance" similar to polkadotJS UI (SS below) - we could probably add this on the "staked amount" card on the overview tab itself

This we discussed on call to do after M2, why are we putting this forward now?

> When trying to bond more funds, I get an error (SS below) - probably because we're using a controller for signing this instead of the stash

We discussed yesterday to do the same using controller account, could you clarify and finalize which account to use for what operation?

Left 2 problems I've taken into account, will fix them next. ETA: 2 PM (Saturday, 4th July)

**Comment by saumyakaran** [comment]
> Could you please elaborate where the loader is not visible, I've taken care of this at most places.

Ah! Apologies for the incomplete info...

1. When bonding additional funds, I'm able to trigger multiple txs by clicking the "confirm" button, even though there's a loader shown beside it
2. In the payment destination, a similar problem, just without the loader
3. Same for unbond funds
4. For edit validators UI, the button still looks clickable, but doesn't do anything [+P3] - feel free to ignore this one for now

> This we discussed on call to do after M2, why are we putting this forward now?

Right, so apologies for that. I realized now that putting this off till M2 wouldn't make sense because of the following:

- The purpose of the overview tab is to serve as a "Stakes monitor"
- Right now, I realized that the call I made for cutting scope, while important, was going too far in some places (especially here). Since, without the dashboard overview functioning properly, I wouldn't really have any proper way to see what happened to the calls that I made.
- Hence, it makes sense for us to keep tx states handling and "stakes monitoring" within the scope - because when submitting the same to W3F, they could get confused about whether the calls are functioning properly or not

Again, my sincerest apologies for the lack of decisiveness 🙏🏻

> We discussed yesterday to do the same using controller account, could you clarify and finalize which account to use for what operation?

"I believe stash is used as the origin account for bonding/unbonding related activities and controller is used as the origin account for changing nominations, chilling and even for changing payment destination" - https://github.com/buidl-labs/yieldscan-frontend/pull/24#pullrequestreview-442156284

**Comment by saumyakaran** [comment]
@akshatbhargava123 Feedback for validator profile

It mostly looks good. A few things that need clarification/revision:

1. Activity tab isn't needed for M2, so we can get rid of that for now.

2. Above the key stats, as shown in design [here](https://www.figma.com/file/n65zoIVgwL847PMyerqkLx/YieldScan-v2-Designs?node-id=1326%3A14578), I would like to have a little input for staking amount which allows me to see potential earnings I could get by staking on this validator.

3. Could you confirm that the bio text that says "Staked runs the most reliable... most proof-of-stake chains." is just a placeholder for now, which will be dynamic after authentication and profile editing is implemented?

The rest looks good.

**Comment by akshatbhargava123** [comment]
ETA for all feedback: Today EOD.

**Comment by saumyakaran** [comment]
@akshatbhargava123 Is there an update on the above?

**Comment by saumyakaran** [comment]
1. Dashboard overview not working (SS attached):
Screenshot 2020-07-06 at 7 36 27 PM

2. For `EX98wxj7cUkpPxcsEsNK9J6qX8N79mv6om8bbjLGnu9Q1ur` validator (maybe for others as well), data doesn't match PolkadotJS (SS below - might require @sahilnanda1995 's attention):

Screenshot 2020-07-06 at 7 45 40 PM
Screenshot 2020-07-06 at 7 45 55 PM

3. When I go back to previous page (advanced selection of validators) after visiting validator profile, I get the following error:

Screenshot 2020-07-06 at 7 48 57 PM

4. For `EDNEfKXHd645DPpBhLZjaEwp4sPhj4STjjS4QrMbFU1FqbZ` validator, it says info couldn't be fetched (might require @sahilnanda1995 's attention):

Screenshot 2020-07-06 at 7 50 48 PM

**Comment by sahilnanda1995** [comment]
>2. For EX98wxj7cUkpPxcsEsNK9J6qX8N79mv6om8bbjLGnu9Q1ur validator (maybe for others as well), data doesn't match PolkadotJS

>4. For EDNEfKXHd645DPpBhLZjaEwp4sPhj4STjjS4QrMbFU1FqbZ validator, it says info couldn't be fetched (might require @sahilnanda1995 's attention):

^ These are because I have turned off data updating for implementing some checks and testing purposes.

**Comment by saumyakaran** [comment]
@akshatbhargava123 PS - The values for "other stake" seem to be different from actual values in the validator table. Seems that "total stake" is being used instead of "other stake".

Validator ID I used: `EDNEfKXHd645DPpBhLZjaEwp4sPhj4STjjS4QrMbFU1FqbZ`

**Comment by akshatbhargava123** [comment]
@saumyakaran , waiting for your go-ahead to merge the PR now.

**Comment by saumyakaran** [comment]
@akshatbhargava123 Feedback:

Mostly looks good to go. A few changes mentioned below:

1. So, this one caught me by surprise. I didn't know that controller is what needs to be used to unbond... My sincerest apologies for this. I didn't know this myself - Seems like everything except bonding/bonding extra funds uses controller - https://polkascan.io/kusama/transaction/0xec50094b514ae3352dcf8758af602fcf8c05975365094c04b5f3b8846d6c46ae

For the unbond call, we need to use the controller as the signer.

2. For the unlocking balance, it only shows 2 digits after the decimal, so I'm not sure if it's connected to the API or not. Could you confirm it that is?

3. The "Stop all nominations" call doesn't seem to be working at all... i.e. no error either - nothing gets logged in the browser console as well.

4. The update controller thing is also not working anymore - same as point 3 - nothing gets logged, no error

5. [+P3] The button for "update controller" after triggering the tx still looks clickable.

**Comment by saumyakaran** [comment]
@akshatbhargava123 Seems good to me from a functionality PoV.

- However, there's just one thing that's bugging me - whenever I send a transaction it keeps me on the loading page for too long - I'm not sure if the popup is closed by itself after tx confirmation or not, if it is then feel free to ignore this point for now.

- It is worth mentioning that I didn't wait for a response on our UI and hence closed the popups pre-maturely, I had the PolkadotJS UI open side by side which I was using to see whether or not the tx actually went through - their UI was instantly updated (ours took a while).

**Comment by akshatbhargava123** [comment]
@saumyakaran ,
> I'm not sure if the popup is closed by itself after tx confirmation or not

Yes, the popups are closed automatically if a tx succeeds so I think it's not longer an issue.

> their UI was instantly updated (ours took a while)

As discussed in today's call, this is the latency from the API due to the network, they are using a realtime subscription when we do the chain state thing, though we're checking if the currently sent tx is actually completed or not and handling it's events data.

> The unlocking balance says 0.0000 even though I have 0.002 KSM unbonding (saw on PolkadotJS)

This is a duplicate issue of data not being real-time to which @sahilnanda1995 mentioned that he had stopped realtime updates due to testing purposes and will be opening it back today.

**Pull request merged**
