### PR TITLE
sprint/week-1-feedback

### LINKED ISSUE #11: Layout getting disturbed when amount input value toooooo big
**Describe the bug**
The layout of the dashboard is getting disturbed when the amount input value is too big, the expected returns card shift towards right hiding some part of it, and then this continues on every state update (amount input value change).

### PR DESCRIPTION
**Pull request by akshatbhargava123**
- closes all [+P1] and some [+P2] issues in #8.
- also fixes #11

### CODE REVIEW

**Comment by saumyakaran** [comment]
```
input_wallet_not_connected
bond_additional_funds_input = input_wallet_not_connected - currently_bonded
```

**Comment by akshatbhargava123** [comment]
ETA for above fixes after discussion: 4PM

**Comment by akshatbhargava123** [comment]
@saumyakaran here's the update:

Except 3 and 4, all are done.
I'll prefer to do 4th when we've got the right design for it, currently, the logo is incorrect. For 3rd we've updated the priority as discussed.

Request you to please test the transaction state one thoroughly because I'm 99% sure it'll work but 1% uncertainty exists there.
Let me know if any other changes are required.

**Comment by saumyakaran** [comment]
@akshatbhargava123 
Screenshot 2020-06-23 at 2 21 51 PM

Steps to recreate:

1. When account isn't connected, switch the input to "No"
2. Connect wallet - this happens

**Comment by saumyakaran** [comment]
> Request you to please manually test the transaction state one because I'm 99% sure it'll work but 1% uncertainty exists there.

Seems alright for now - although I would have preferring showing the user what exactly went wrong (similar to PolkadotJS UI)

**Comment by akshatbhargava123** [comment]
@saumyakaran ETA for following:
- [ ] Show logo of the network in the header
- [ ] compounding UI bug

**Comment by akshatbhargava123** [comment]
@saumyakaran I've pushed the required changes, please allow me to merge the PR now.

**Pull request merged**
