### PR TITLE
sprint/milestone-2

### LINKED ISSUE #19: Fix the filtering and sorting problems with advanced-edit view
Fix the filtering and sorting problems with advanced-edit view when we go to validators-list from calculator page.

### PR DESCRIPTION
**Pull request by akshatbhargava123**
- [x] Edit validators functionality
- [x] Validators list
- [x] Advanced Edit validators
- [ ] Validator profile view [not done in week-2, shifted to next sprint]
~Nominators list~

closes #19

### CODE REVIEW

**Comment by saumyakaran** [comment]
@akshatbhargava123 I can see that you've added todos for nominators list and nominators profile, but not for governance tab and council members profile - I wanted to confirm if you're on the same page that nominators' tab is lower priority than governance tab and council members profile. Also, nominators profile isn't a part of milestone 2

**Comment by akshatbhargava123** [comment]
@saumyakaran requesting you to please check the deployed version now. Let me know if an overview from my side is required, thanks!

**Comment by saumyakaran** [comment]
@akshatbhargava123 It mostly looks good. I just have the following concerns:

- [ ] The own stake filter doesn't seem to be working
- [ ] I don't see a column for `nominators` which displays the number of nominators for each validator but the filter seems to be doing something - although I can't be sure if it's working properly due to the same

[GOOD TO HAVE]

- [ ] I would like to have the inputs for filters pre-filled by default which include all validators - i.e. "high" setting for risk, maximum and minimum possible stake inputs pre-filled, max commission, etc. (if you do implement this, then probably it would also make sense to change "clear filters" text to "reset filters")

- [ ] No back button to head back to the returns calculator (probably also add a popup when clicking back that informs the user that their selections would be lost)

PS - I love the "clear filters" button that you've added 🎯

Apart from these, it's pretty much good to go.

Great job @akshatbhargava123 !

**Comment by akshatbhargava123** [comment]
@saumyakaran 

>The own stake filter doesn't seem to be working
The values are currently hardcoded and an issue with P1 priority on the backend is already open.

Will update for other points, ETA: EOD today (30th June)

**Comment by saumyakaran** [comment]
@akshatbhargava123 Regarding the backend issue for own stake - @sahilnanda1995 has moved it to "Done" on the zenhub pipeline.

@akshatbhargava123 Are you still facing problems with the API? If yes, then please brief @sahilnanda1995 on the same so he can help.

**Comment by akshatbhargava123** [comment]
@saumyakaran, the need-to-have concerns have been fixed. Thanks for getting it to notice that `ownStake` is already coming from the API, I should have taken care of it.

Btw this now also closes #21 .

Need go-ahead from your side to merge this PR now :)

**Comment by saumyakaran** [comment]
@akshatbhargava123 Looks good to me. Great job! 🎉

**Pull request merged**
