### PR TITLE
m2-resubmission-2

### LINKED ISSUE #44: [FEATURE REQUEST] Add a runner-ups section to the governance tab
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

It would be nice to also show the runner-ups in the governance tab.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### LINKED ISSUE #49: [BUG] Overview tab breaks with large KSM amounts
**Describe the bug**

Regarding the larger KSM amounts error. 
- I receive it on the dashboard. 
- With the live version I get the following error in the console, when I try to connect to the wallet: “Uncaught (in promise) Error: Number can only safely store up to 53 bits”, so I expect the error happens when the wallet contains a larger amount of tokens.

**Screenshots**

image

**Additional context**

My speculation is that there's only so many places for our implementation to break:

1. If the locked balance is very large
2. If the freeBalance is very large
3. If the unlocking balance is very large

I really don't see any other way for the overview tab to break - perhaps we could do what Prastut suggested and simulate the test with fake data to ensure that these points don't break down when hit with large amounts of KSM (refer [this](https://docs.google.com/document/d/1tHkFRb5N8oibMsdGvCYJNIOX1tYJpIApOZW6E1pEgws/edit?disco=AAAAKBleZgQ))

### LINKED ISSUE #50: [FEATURE REQUEST] Nominations tab in overview page
Viewing all current nominations in a separate tab in the overview with data.

### LINKED ISSUE #51: [FEATURE REQUEST] Real-time data in overview tab and global balance
The following data in the app should be real-time:
- [x] All types of balances: unlocking, free, bonded
- [x] Nominations

### PR DESCRIPTION
**Pull request by akshatbhargava123**
closes #51 ,
closes #50 ,
closes #44 ,
closes #49 .

### CODE REVIEW

**Comment by saumyakaran** [comment]
When I go to David's profile under the runner ups tab, then click "Own this profile" thing, then connect my wallet, the page breaks and I get the following error on my browser console: 

Screenshot 2020-07-30 at 11 24 51 AM

**Comment by saumyakaran** [comment]
@akshatbhargava123 PS - Can we change "* Estimated Returns are calculated per era for 100 KSM" text on the "My validators" tab to be just "* Estimated Returns are calculated per era" - since we're calculating for the stake amount that we've mentioned, not really for "100 KSM"

**Comment by akshatbhargava123** [comment]
@saumyakaran , now waiting for your go-ahead to merge the PR.

**Comment by saumyakaran** [comment]
- So the profiles work after connection now, however I'd like to test the "edit" functionality - is there a way I could do that?

- [The PR can be closed without addressing this point - we could shift this to a new issue since I'm not sure how to recreate this] In the overview tab, the popups (bond extra, unbond as well as change nominations popups) seem to only show 3 of my nominations, when in fact I have 4 (SS attached below) - also, once I changed my nominations, it was working fine, so not sure how to recreate this

Screenshot 2020-07-31 at 11 01 01 AM
Screenshot 2020-07-31 at 11 01 38 AM

-[The PR can be closed without addressing this point - we could shift this to a new issue] In the above image, notice the "Estimated Monthly Returns" says 0, while the "estimated reward" for each validator is between 1.6 to 2.1 KSM
    - [Design problem] Specifically, from a user PoV I don't know for what time period these returns are calculated
    - [Question from technical stand point] What is "Estimated Reward" for each validator? i.e. how are we calculating that? And isn't "Estimated Monthly Returns" a sum of those rewards? 

- [If this is a backend issue, the PR can be closed without addressing this point - we could shift this to a new issue on the backend] Also, seems like there's some issue with the own/other stake data (probably a backend issue - cc @sahilnanda1995):

Screenshot 2020-07-31 at 10 58 21 AM

**Comment by akshatbhargava123** [comment]
@saumyakaran, changes pushed.

**Comment by saumyakaran** [comment]
@akshatbhargava123 

- [ ] Getting the text "no nominations" on the "All nominations" tab even though I have 16 selected nominations as seen in the "edit validators popup":

Screenshot 2020-07-31 at 9 54 04 PM
Screenshot 2020-07-31 at 9 53 56 PM

- [ ] Is it possible to remove the hard-coded USD amounts displayed on the bond/unbond popups?

>  Check for null ownStake and otherStake values wherever we show the api/risk-set data and replace 0 values with a dash ('-').

- [ ] For the above, the profile for the same still seems to break + they're displayed at the top of the list by default which makes it that much easier for the user to click on their profile

>  Change "Estimated Reward" text (in all popups which use "Estimated pool reward" for display) to "Estimated Pool Reward"

This doesn't seem to be addressed in edit validators popup.

**Comment by akshatbhargava123** [comment]
> For the above, the profile for the same still seems to break + they're displayed at the top of the list by default which makes it that much easier for the user to click on their profile

Not able to reproduce.

> Is it possible to remove the hard-coded USD amounts displayed on the bond/unbond popups?

Not able to reproduce.

Could you please provide more information on the above issues?

**Comment by saumyakaran** [comment]
> For the above, the profile for the same still seems to break + they're displayed at the top of the list by default which makes it that much easier for the user to click on their profile

For this, there no longer seems to be any validator in the set which has "-" as the value for "other stake", for me it only broke for those validators.

> Is it possible to remove the hard-coded USD amounts displayed on the bond/unbond popups?

Screenshot 2020-08-01 at 11 04 57 AM
Screenshot 2020-08-01 at 11 05 50 AM

**Comment by saumyakaran** [comment]
@akshatbhargava123 I just noticed that the "Estimated Monthly Returns" shown in the popups seem unrealistic (all 3 popups - unbond, bond more and edit validators) - attached SS for edit validators popup, the other 2 also have similar unrealistic returns:

Screenshot 2020-08-01 at 2 25 16 PM

**Comment by akshatbhargava123** [comment]
Fixed, merging the PR now.

**Pull request merged**
